services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlineStore
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      POSTGRES_DB: onlineStore
    env_file:
      - .env
    ports:
      - 8080:8080

volumes:
  postgres_data:
